sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME=pallavkothari/hello-travis

before_script:
  # Print build info that binary is compiled with.
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  # pull docker image to use as cache below
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME":pr .

after_script:
  - docker images

before_deploy:
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - if [ ! -z "$TRAVIS_TAG" ]; then export IMAGE_TAG=$TRAVIS_TAG; else export IMAGE_TAG=${GIT_SHA}-${TRAVIS_BRANCH}; fi
  - docker tag "$IMAGE_NAME":pr "$IMAGE_NAME":"$IMAGE_TAG";
  - docker tag "$IMAGE_NAME":pr "${IMAGE_NAME}:latest"
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push "$IMAGE_NAME":"$IMAGE_TAG" && docker push "${IMAGE_NAME}:latest"
  on:
    all_branches: true